#ifndef __LIBXL_TYPES_JSON_H
#define __LIBXL_TYPES_JSON_H

/*
 * DO NOT EDIT.
 *
 * This file is autogenerated by
 * "gentypes.py libxl_types.idl __libxl_types.h __libxl_types_json.h __libxl_types.c"
 */

yajl_gen_status libxl_domain_type_gen_json(yajl_gen hand, libxl_domain_type *p);
yajl_gen_status libxl_device_model_version_gen_json(yajl_gen hand, libxl_device_model_version *p);
yajl_gen_status libxl_console_type_gen_json(yajl_gen hand, libxl_console_type *p);
yajl_gen_status libxl_disk_format_gen_json(yajl_gen hand, libxl_disk_format *p);
yajl_gen_status libxl_disk_backend_gen_json(yajl_gen hand, libxl_disk_backend *p);
yajl_gen_status libxl_nic_type_gen_json(yajl_gen hand, libxl_nic_type *p);
yajl_gen_status libxl_action_on_shutdown_gen_json(yajl_gen hand, libxl_action_on_shutdown *p);
yajl_gen_status libxl_trigger_gen_json(yajl_gen hand, libxl_trigger *p);
yajl_gen_status libxl_tsc_mode_gen_json(yajl_gen hand, libxl_tsc_mode *p);
yajl_gen_status libxl_timer_mode_gen_json(yajl_gen hand, libxl_timer_mode *p);
yajl_gen_status libxl_bios_type_gen_json(yajl_gen hand, libxl_bios_type *p);
yajl_gen_status libxl_scheduler_gen_json(yajl_gen hand, libxl_scheduler *p);
yajl_gen_status libxl_shutdown_reason_gen_json(yajl_gen hand, libxl_shutdown_reason *p);
yajl_gen_status libxl_vga_interface_type_gen_json(yajl_gen hand, libxl_vga_interface_type *p);
yajl_gen_status libxl_ioport_range_gen_json(yajl_gen hand, libxl_ioport_range *p);
yajl_gen_status libxl_vga_interface_info_gen_json(yajl_gen hand, libxl_vga_interface_info *p);
yajl_gen_status libxl_vnc_info_gen_json(yajl_gen hand, libxl_vnc_info *p);
yajl_gen_status libxl_spice_info_gen_json(yajl_gen hand, libxl_spice_info *p);
yajl_gen_status libxl_sdl_info_gen_json(yajl_gen hand, libxl_sdl_info *p);
yajl_gen_status libxl_dominfo_gen_json(yajl_gen hand, libxl_dominfo *p);
yajl_gen_status libxl_cpupoolinfo_gen_json(yajl_gen hand, libxl_cpupoolinfo *p);
yajl_gen_status libxl_vminfo_gen_json(yajl_gen hand, libxl_vminfo *p);
yajl_gen_status libxl_version_info_gen_json(yajl_gen hand, libxl_version_info *p);
yajl_gen_status libxl_domain_create_info_gen_json(yajl_gen hand, libxl_domain_create_info *p);
yajl_gen_status libxl_domain_sched_params_gen_json(yajl_gen hand, libxl_domain_sched_params *p);
yajl_gen_status libxl_domain_build_info_gen_json(yajl_gen hand, libxl_domain_build_info *p);
yajl_gen_status libxl_device_vfb_gen_json(yajl_gen hand, libxl_device_vfb *p);
yajl_gen_status libxl_device_vkb_gen_json(yajl_gen hand, libxl_device_vkb *p);
yajl_gen_status libxl_device_disk_gen_json(yajl_gen hand, libxl_device_disk *p);
yajl_gen_status libxl_device_nic_gen_json(yajl_gen hand, libxl_device_nic *p);
yajl_gen_status libxl_device_pci_gen_json(yajl_gen hand, libxl_device_pci *p);
yajl_gen_status libxl_domain_config_gen_json(yajl_gen hand, libxl_domain_config *p);
yajl_gen_status libxl_diskinfo_gen_json(yajl_gen hand, libxl_diskinfo *p);
yajl_gen_status libxl_nicinfo_gen_json(yajl_gen hand, libxl_nicinfo *p);
yajl_gen_status libxl_vcpuinfo_gen_json(yajl_gen hand, libxl_vcpuinfo *p);
yajl_gen_status libxl_physinfo_gen_json(yajl_gen hand, libxl_physinfo *p);
yajl_gen_status libxl_numainfo_gen_json(yajl_gen hand, libxl_numainfo *p);
yajl_gen_status libxl_cputopology_gen_json(yajl_gen hand, libxl_cputopology *p);
yajl_gen_status libxl_sched_credit_params_gen_json(yajl_gen hand, libxl_sched_credit_params *p);
yajl_gen_status libxl_domain_remus_info_gen_json(yajl_gen hand, libxl_domain_remus_info *p);
yajl_gen_status libxl_event_type_gen_json(yajl_gen hand, libxl_event_type *p);
yajl_gen_status libxl_event_gen_json(yajl_gen hand, libxl_event *p);

#endif /* __LIBXL_TYPES_JSON_H */
