#!/bin/bash
#
#  xcp-networkd        Startup script for network management service
#
# chkconfig: 2345 13 88
# description: Manages host networking for VMs.
### BEGIN INIT INFO
# Provides: xcp-networkd
# Required-Start: $local_fs $network $syslog message-switch
# Required-Stop: $local_fs $syslog
# Should-Start: $syslog message-switch
# Should-Stop: $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Network management service
# Description:       Manages host networking for VMs.
### END INIT INFO

# Source function library.
. /etc/init.d/functions

RETVAL=0
PIDFILE=/var/run/xcp-networkd.pid

prog=xcp-networkd
exec=/usr/sbin/xcp-networkd
if [ -d /var/lock/subsys ] ; then
    lockfile=/var/lock/subsys/$prog
else
    lockfile=/var/lock/$prog
fi

# Source config
if [ -f /etc/sysconfig/$prog ] ; then
    . /etc/sysconfig/$prog
fi

start() {
	[ -x $exec ] || exit 5

	umask 077

        echo -n $"Starting xcp-networkd: "
        daemon --pidfile="$PIDFILE" $exec -pidfile "$PIDFILE" -daemon true $XCP_NETWORKD_OPTIONS
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch $lockfile
        return $RETVAL
}
stop() {
        echo -n $"Shutting down xcp-networkd: "
        killproc -p "$PIDFILE" $exec
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f $lockfile
        return $RETVAL
}
rhstatus() {
        status -p "$PIDFILE" -l $prog $exec
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  reload)
        exit 3
        ;;
  force-reload)
        restart
        ;;
  status)
        rhstatus
        ;;
  condrestart|try-restart)
        rhstatus >/dev/null 2>&1 || exit 0
        restart
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|condrestart|try-restart|reload|force-reload|status}"
        exit 3
esac

exit $?
