#!/bin/bash
#
#  xenopsd-xc        Startup script for xenopsd-xc service
#
# chkconfig: 2345 13 88
# description: Manages xen domains via libxc
### BEGIN INIT INFO
# Provides: xenopsd-xc
# Required-Start: $local_fs $network $syslog message-switch forkexecd xen
# Required-Stop: $local_fs $syslog
# Should-Start: $syslog message-switch forkexecd
# Should-Stop: $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Manages xen domains via libxc
# Description:       Manages xen domains via libxc
### END INIT INFO

# Source function library.
. /lib/lsb/init-functions

RETVAL=0
PIDFILE=/var/run/xenopsd-xc.pid

prog=xenopsd-xc
exec=/usr/sbin/xenopsd-xc
if [ -d /var/lock/subsys ] ; then
    lockfile=/var/lock/subsys/$prog
else
    lockfile=/var/lock/$prog
fi

# Source config
if [ -f /etc/sysconfig/$prog ] ; then
    . /etc/sysconfig/$prog
fi

# ensure that all the possible xen directories are on the XCP_PATH
export XCP_PATH=/usr/lib/xen/bin:/usr/lib/xen-4.3/bin:/usr/lib/xen-4.2/bin:/usr/lib/xen-4.1/bin:/usr/lib/xen/boot:/usr/lib/xen-4.3/boot:/usr/lib/xen-4.2/boot:/usr/lib/xen-4.1/boot

start() {
	[ -x $exec ] || exit 5

	umask 077

	modprobe blktap 2>/dev/null || logger -t xenopsd-xc "Failed to modprobe blktap: vhd-based disks will not work"
	modprobe blkback 2>/dev/null || logger -t xenopsd-xc "Failed to modprobe blkback: virtual disks will not work"
        echo -n $"Starting xenopsd-xc: "
        start_daemon -p "$PIDFILE" $exec -pidfile "$PIDFILE" -config /etc/xenopsd.conf -daemon true $XENOPSD_XC_OPTIONS
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch $lockfile
        return $RETVAL
}
stop() {
        echo -n $"Shutting down xenopsd-xc: "
        killproc -p "$PIDFILE" $exec
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f $lockfile
        return $RETVAL
}
rhstatus() {
        status_of_proc -p "$PIDFILE" $exec $prog
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  reload)
        exit 3
        ;;
  force-reload)
        restart
        ;;
  status)
        rhstatus
        ;;
  condrestart|try-restart)
        rhstatus >/dev/null 2>&1 || exit 0
        restart
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|condrestart|try-restart|reload|force-reload|status}"
        exit 3
esac

exit $?
